# Generated by Django 3.2.7 on 2021-11-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_destination_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='rating',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
