# Generated by Django 3.2.7 on 2021-11-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_destination_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Place', models.CharField(max_length=100)),
                ('decr', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='photos')),
                ('price', models.FloatField()),
                ('offer', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
