# Generated by Django 3.2.7 on 2021-11-24 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_upcomingoffers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upcomingoffers',
            old_name='price',
            new_name='amt',
        ),
        migrations.RenameField(
            model_name='upcomingoffers',
            old_name='offer',
            new_name='offr',
        ),
        migrations.RenameField(
            model_name='upcomingoffers',
            old_name='image',
            new_name='pic',
        ),
        migrations.RenameField(
            model_name='upcomingoffers',
            old_name='rating',
            new_name='ratings',
        ),
    ]
